### ISSUE TITLE
Unable to create file cifar10_tmp.hdf5

### ISSUE THREAD

**Issue by nthuann** [Whadup/xai_tracking#1]
When trying to run `python -m cifar10.train`, I got this error
![image](https://user-images.githubusercontent.com/48089731/137613297-e0f37e46-3d99-4932-b36c-4ecae3f7af03.png)

And one of the thing i don't understand in file **cifar10/train.py** is in the line **71**, there's a path to a file like this `"/raid//cifar10_tmp.hdf5"`, I don't know if the author miss added one more "/" in that path.
I tried to create **raid** folder manually, in both root folder **xai_tracking** and **cifar10** folder, then create **cifar10_tmp.hdf5** file, as well as remove one "/" in the path on line **71** and run the code, but still got the same error as above image.

Hope someone can help me out with this.
Thanks

**Comment by Whadup** [comment]
You're absolutely right, that second / was added by mistake. The folder /raid should be available on your system, if that doesn't work just change the paths to some other directory where you have write access.

**Comment by nthuann** [comment]
Thank you so much
